### ISSUE TITLE
php ext-gd are missing ?

### ISSUE THREAD

**Issue by xanscale** [flathub/org.freedesktop.Sdk.Extension.php84#1]
i don't know if ext-gd is a large use library but using composer inside php flatpak sandbox i receive this error

```
sh-5.2$ composer update
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires phpoffice/phpspreadsheet ^3.3 -> satisfiable by phpoffice/phpspreadsheet[3.3.0, 3.4.0, 3.5.0].
    - phpoffice/phpspreadsheet[3.3.0, ..., 3.5.0] require ext-gd * -> it is missing from your system. Install or enable PHP's gd extension.
  Problem 2
    - Root composer.json requires mpdf/mpdf ^8.2 -> satisfiable by mpdf/mpdf[v8.2.0, ..., v8.2.5].
    - mpdf/mpdf v8.2.0 requires php ^5.6 || ^7.0 || ~8.0.0 || ~8.1.0 || ~8.2.0 -> your php version (8.4.1) does not satisfy that requirement.
    - mpdf/mpdf[v8.2.1, ..., v8.2.4] require php ^5.6 || ^7.0 || ~8.0.0 || ~8.1.0 || ~8.2.0 || ~8.3.0 -> your php version (8.4.1) does not satisfy that requirement.
    - mpdf/mpdf v8.2.5 requires ext-gd * -> it is missing from your system. Install or enable PHP's gd extension.

To enable extensions, verify that they are enabled in your .ini files:
    - /usr/lib/sdk/php84/etc/php/php.ini
    - /usr/lib/sdk/php84/etc/php/conf.d/10-opcache.ini
    - /usr/lib/sdk/php84/etc/php/conf.d/15-xdebug.ini
    - /usr/lib/sdk/php84/etc/php/conf.d/40-apcu.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-gd` to temporarily ignore these required extensions.
```

in debian installing "php-gd" package fixes this error.

there is a way to install inside flatpak ?
if this lib are commonly used why not add in this extension by default ?

**Comment by Lctrs** [comment]
Goal of this extension is just to include the bare minimum to be able to run development tools written in PHP such as PHPStan, Psalm, phpactor, etc. to enhance developer experience in the different IDEs. Its goal is not to provide a full environment to run projects as we cannot provide all existing PHP extensions and there are much better tools for this in the containerized world : docker and podman.

**Comment by Lctrs** [comment]
That being said, if you want to be able to just install/update quickly the dependencies of your project, you can just run `composer install --ignore-platform-req=ext-*` (syntax is supported since composer `>=2.2`). It'll ignore the required extensions while still respecting your PHP requirement.
